server:
  port: 81

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 12345678
    virtual-host: /

zuul:
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    connection-request-timeout-millis: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 120000
  shareSecurityContext: true

ribbon:
  readTimeout: 30000
  connectTimeout: 30000
  eager-load:
    enabled: true

logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.bus: debug
    com.scott.neptune: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
