spring:
  profiles:
    active: dev
  application:
    name: gateway
  messages:
    basename: i18n/messages

  #解决springboot配置@ControllerAdvice不能捕获NoHandlerFoundException(404特定格式返回)
  mvc:
    #抛出异常
    throw-exception-if-no-handler-found: true
  resources:
    #关闭资源文件建立映射
    add-mappings: false

eureka:
  instance:
    prefer-ip-address: true

zuul:
  prefix: /v1
  #过滤客户端附带的Headers
  sensitiveHeaders: "*"
  routes:
    user-server: /user-server/**
    score-server: /score-server/**