server:
  port: 8764
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: 12345678
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

